### ISSUE TITLE
No sound on Opera

### ISSUE THREAD

**Issue by lastorset** [scottschiller/SoundManager2#110]
I'm using Opera 32 for Linux without Flash. I'm getting no sound from [DuoLingo](https://www.duolingo.com/comment/3245465) or the demos on the site (e. g. [360º player](http://www.schillmania.com/projects/soundmanager2/demo/360-player/)). Chrome, also on Linux, plays them fine (whether or not Flash is enabled, though it always states it's using HTML5 anyway).

Opera's console has
```
soundmanager2.js:1295 basicMP3Sound1: HTML5 error, code 4
soundmanager2.js:1293 basicMP3Sound1: Failed to load / invalid sound? Zero-length duration reported. (http://www.schillmania.com/projects/soundmanager2/demo/_mp3/office_lobby.mp3)
```

It seems [Opera is officially supported](http://www.schillmania.com/projects/soundmanager2/doc/technotes/#requirements), but all version numbers refer to Opera before we switched to Blink. I initially suspected UA sniffing, but it appears to be done responsibly (targeting only versions < 10).

**Comment by scottschiller** [comment]
Ah-ha. Note that HTML5 error 4 = `MEDIA_ERR_SRC_NOT_SUPPORTED`, so it's likely that Opera is unable to decode the format you're trying to play - MP3 in this case, if you're looking at most of the SM2 demos.

Opera may return "maybe" or "probably" when testing for support for MP3 via `new Audio().canPlayType('audio/mp3')`, but then fail to actually decode when it attempts to load. Since you're on Linux, this may also depend on MP3 support being installed at the OS level.

If SM2 cannot play MP3 via HTML5, by default it will try to load and use Flash behind the scenes to get MP3 support. However, it is possible SM2 can start using only HTML5 and no MP3 if MP3 support is not required, and Flash is not available (i.e., not installed at all, or blocked.) This case makes things a bit more complicated, but it is up to the site developer to handle the case where SM2 fails to start with MP3 support and notify the user accordingly that sounds will have to be downloaded, etc., to play.

If on Ubuntu, you may be able to get MP3 support at the OS level (and thus possibly in Opera) by installing the gstreamer/MP3-related codecs here.
http://askubuntu.com/questions/30163/how-to-install-the-most-common-plugins

Sorry it isn't simpler! :stuck_out_tongue:

**Comment by lastorset** [comment]
Thanks for the detailed response! Researching your idea about Opera and system codecs, I found some funny timing: turns out Opera Beta just started [using Chromium codecs on Wednesday](http://blogs.opera.com/desktop/2015/10/opera-beta-33-0-1990-35-update/)! Installing that update or the latest Opera Developer works fine.

Interestingly, installing *ubuntu-restricted-extras* (that includes the "bad" GStreamer codecs) had no effect.

Taking the liberty of closing this, since this is fixed by an Opera update. Anyone affected can look forward to Opera 33, released in a few weeks.
