### ISSUE TITLE
Download music link does not work with firefox

### ISSUE THREAD

**Issue by tropicaldev** [scottschiller/SoundManager2#113]
In the Bar Ui examples  here http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/ 
it's missing the atribute "download" in the link so download does not work in none of the browsers.

Adding "download" atribute  to the link with Chrome,IE or Edge the download just starts fine but 
with FireFox it opens a blank page and the music starts playing

**Comment by ZaheerAghani** [comment]
Download link redirect me to next page nd then mp3 start to play...
how can i just make mp3 to just download.

**Comment by scottschiller** [comment]
Pardon the late follow-up, here. SM2 is doing the right thing here in allowing the browser to follow the link directly to the MP3, etc... The problem is that the browser is deciding to play the file using its built-in player, rather than giving a download / "save as" prompt.

Assuming you control the server, you will want to add a `content-disposition` HTTP response header to force the browser to download the file, "save as..." style (or automatically save to `~/downloads` or whatever, depending on the browser / OS / preferences.)

http://stackoverflow.com/questions/9195304/how-to-use-content-disposition-for-force-a-file-to-download-to-the-hard-drive
