### ISSUE TITLE
onload event is not deterministic

### ISSUE THREAD

**Issue by magne4000** [scottschiller/SoundManager2#118]
`onload` event should fire only when audio is fully loaded, even in HTML5 mode, in order to have the same behavior with HTML5 and Flash.
This generates a side effect: It's impossible to know, in HTML5 mode, when a track is fully loaded (with `stream: true`)

**Comment by scottschiller** [comment]
A valid point! I also thought the same when I was first working on the HTML5 implementation within SM2.

However, note that HTML5 uses HTTP byte ranges / partial requests by default vs. a single, contiguous request for the entire sound asset - so it is not realistic to have `onload` represent "fully loaded" as in the Flash case, or as one would expect when loading an image or making an XHR etc. In fact, HTML5 clients may not even download the full file if the user doesn't play it all the way through to the end.

HTML5 fires `canplay` when it has determined that the sound can be decoded by the OS and has loaded enough to start playback, and then `canplaythrough` when network conditions and load progress look like the browser can play the rest of the audio/video without having to stop playback to buffer.

Therefore, I optimistically have the SM2 `onload` event fire at `canplay`. OTOH I originally looked at `canplaythrough`, but that event may take playback to really work.

Thanks to partials / byte serving, HTML5 has the advantage of being able to arbitrarily seek to any point in a file (audio, or video) like on YouTube, pretty quickly. Instead of a single request, it buffers ranges of data on demand. This is driven and controlled entirely by the browser / and network.

You can also specify various forms of preloading for HTML5 audio, but it is up to the browser to determine how much it may actually preload. It's unlikely that it will fetch the whole file up front, before playback starts.

I should note that `stream: true` only applies to Flash, that's a very old-skool Flash 8-era loading option. I wouldn't recommend using it, instead just going for a simple preload approach like `mySound.load({ onload: function() { this.play(); } });` or what have you.

Ultimately, preloading doesn't really matter unless you have a very specific use case, e.g., sound effects for a game or some case where you really need to guarantee a resource is 100% available before its first use.

More here on the ways clients get audio, if you're curious.
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#client-requests

**Comment by magne4000** [comment]
My point is still valid :), I think that there should be another event to differenciate "I'm ready to play" and "I'm fully loaded".

Here is my use case:
I have a list of tracks to play one after another. When the first track is ready to be played, it plays. When this track is "fully loaded", I want to begin loading the next track in the playlist, but I can't rely on the `onload` event of the first track for that, because it'll possibly load 2 tracks in parallel (and by so possibly slow down the loading of the first track).

**Comment by scottschiller** [comment]
Quoting Doc Brown here, "Marty, you're just not thinking fourth-dimensionally!" :stuck_out_tongue:
Alternately, "How I learned to stop worrying and love the way HTML5 downloads audio", etc.

Traditional progressive downloading (and preloading) simply appears to be considered an anti-pattern for HTML5 audio/video per the W3 spec, as it doesn't work the way you'd like. If you want a sequential, single-request download pattern, you will have to hack around HTML5's design to get it in.

You have to also consider mobile devices, which generally block auto-play and restrict pre-loading of `<audio>` and `<video>` by design. Or at least, they are unlikely to pre-load the whole file unless it's small. Forcing a mobile client to download a large file it may not use is wasteful and not considerate of the user's mobile cache or bandwidth, especially if they are on a cellular plan with only a small amount of data.

Moving on to actual client events... The closest event to "fully loaded" for your case would be the HTML5 `canplaythrough` event, which means the UA _expects_ it should be able to play the file through without having to stop to buffer. There is no native property to force a complete preload, nor an event for "fully loaded."

Depending on the UA, sometimes the HTML5 `progress` event provides a `buffered` property, and/or `timeRanges` implementation - possibly the closest you can get to determining "how much has loaded." However, again, it is unlikely to be sequential blocks of time / bytes that have loaded because of the way HTML5 requests data over the network. Additionally, and not surprisingly, browser support and implementations of these properties varies somewhat.

https://developer.mozilla.org/en/DOM/TimeRanges

_So!_ ... With all that said, basically, you cannot expect nor rely on an HTML5 `<audio>` (or `Audio()`) object to use a single HTTP/S request and preload / download all at once. However, there are two possible ways to work around this.

1) Configure your server to _not_ support byte ranges / HTTP partial requests in its responses for MP3 and related audio files. In this case, clients _should_ fall back to using a single request for the entire file, and thus one request = load the entire thing from 0-100% in sequence.

So instead of `Accept-Ranges: bytes`, you would have your server return `Accept-Ranges: none`. I've never tested this, and I wouldn't be surprised if there are differences across browsers and mobile devices when they get a server response like this, but ¯\_(ツ)_/¯

2) Preload the MP3 (or related) file using a traditional browser file request method, like `new Image('some.mp3')`, or an `XMLHttpRequest()`, or even a hidden `<img>`. There is a chance that browsers will cache that request, even if they cannot parse it for use as an image etc., and a subsequent HTML5 request will recognize and use the MP3 from cache. It is possible that HTML5 will still appear to use byte ranges and load only what's needed, but will still be pulled from the local disk cache vs. using the network.

In either case, you are trying to work against HTML5 and that should be seen as a red flag. I also like the idea of preloading and assuring that sound will be available before it's requested, but I've come to realize that HTML5 is smarter than me with regards to preloading and managing buffering, etc., and doing so in an entirely transparent fashion.

It is highly unlikely to see playback stop to buffer unless there is something wrong with the network or route. Effectively, it's best to not worry about how HTML5 loads content - it's quite good about it, and unlike a single request, can better account for bad network conditions (like dropped connections, spotty wifi, and so on.)
