### ISSUE TITLE
audio doesn't start when there is pending request

### ISSUE THREAD

**Issue by seansay** [scottschiller/SoundManager2#127]
it seems that the audio doesn't start play until all the request is finish, is that right?

**Comment by seansay** [comment]
for example , if somehow ga  script is pending, this will not play until the script is loaded.

cc @scottschiller

**Comment by scottschiller** [comment]
Apologies for super-late reply, very busy with professional work.

HTML5 audio requests (or even Flash-initiated ones) should go through the regular browser pipeline. The browser could be blocking and queueing network connections just because there are X simultaneous requests per-domain, that is one possibility.

It's also possible if Google Analytics is taking an ice age to load, _and_ is blocking DOMReady / DOMContentLoaded / whatever it is these days 😆, that could block SM2 from starting up and subsequently loading + playing its first sound (e.g., you have something set up to create + play right away.)

GA should load async though and not block DOM etc., these days. Make sure you're using their `async` loader if not already.
