### ISSUE TITLE
Huge iOS 9 bug

### ISSUE THREAD

**Issue by a4jp-com** [scottschiller/SoundManager2#128]
SoundManager 2 doesn't work on iOS devices 9 and up properly anymore. Sounds play but there is a bug in the iOS software that cuts sounds off when files are played. It looks like there is a fix for this though. WordPress also has the same problem and they are working on a fix now.

https://core.trac.wordpress.org/ticket/36374#comment:12

**Comment by scottschiller** [comment]
Boo. :ghost: Thanks for the report; will take a look this weekend.

**Comment by a4jp-com** [comment]
Thank you very much. 

I'm making a study program and have used SoundManager2 for the audio player. 

You can see it here (http://agreatdream.com/quiz34test.php) if you would like to have a look.

**Comment by scottschiller** [comment]
From what I see, the issue is your web server. There is something that Safari on desktop OS X does also not like about the way your MP3 files are being served from your web server.

In testing on an iPhone running iOS 9.3.1, I haven't any problems on the SM2 homepage itself. It seems to be fine.

This file that you serve, for example, refuses to play all the way through when loading directly in Safari.
http://agreatdream.com/quiz/audio/watermelon.mp3

_However_, if I download the MP3 file ("save as" from Safari's built-in player) and then drag-and-drop the MP3 into Safari, it plays just fine.

Your server is returning this in its HTTP response headers:
```
Accept-Ranges:bytes
Cache-Control:max-age=86400
CF-RAY:28d8e0002d370651-SJC
Connection:keep-alive
Content-Encoding:gzip
Content-Length:1
Content-Range:bytes 12778-12778/13452
Content-Type:audio/mpeg
Date:Sun, 03 Apr 2016 01:51:21 GMT
Expires:Mon, 04 Apr 2016 01:51:21 GMT
Last-Modified:Mon, 09 Apr 2012 08:44:48 GMT
Server:cloudflare-nginx
Vary:Accept-Encoding
```

Looks like something is mis-configured there. A few issues I see:

*Content-Encoding:gzip* - don't gzip MP3 and other binary files, it is likely a contributor to this issue. Only gzip text like HTML, CSS, JavaScript etc.

*Content-Length: 1*
This doesn't seem right either and may be related to the gzip header issue.

*Content-Range:bytes 12778-12778/13452*
Hard to say what's going on here, but it also seems invalid. Your server is returning a 0-byte range? Again, probably due to gzip being enabled.

I suspect if you don't serve MP3s etc. with gzip, things will be OK.

Side note: HTML5 clients will use byte serving (byte ranges / partials) by default, where supported. More on how clients request audio, here.
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#client-requests
