### ISSUE TITLE
bower ENOTFOUND     Package SoundManager2 not found

### ISSUE THREAD

**Issue by rohan-deshpande** [scottschiller/SoundManager2#135]

**Comment by scottschiller** [comment]
Pardon super-late reply, have been very busy with professional work. 😅 

It's entirely possible I'm a dummy and when I published the last version of SM2, had to push an `-a` revision on NPM.
https://www.npmjs.com/package/soundmanager2

**Comment by Gerfaut** [comment]
If needed, this can work too :)
`bower install https://github.com/scottschiller/SoundManager2#V2.97a.20150601 --save`

**Comment by scottschiller** [comment]
I've just pushed an SM2 update, and was able to install SM2 via `bower` on my machine; I did get some warnings about the package naming convention, but I was hesitant to change `bower.json` in the event I might cause problems for users with existing installs.

I added `bower.json` quite some time back, so the format may have evolved since. If it can be updated in a way that still works for everyone, do let me know and I'll fix it up! 🙇
