### ISSUE TITLE
Detecting network disconnecting during HTML5 playback

### ISSUE THREAD

**Issue by vitalybe** [scottschiller/SoundManager2#142]
I am using SoundManager2 with HTML5 audio and I am unable to properly detect and handle disconnections.

Here is the flow:
1. I'm calling `createSound` function and after a while get the `onload` callback
2. I'm calling the `play` function and it starts playing. At this point the 30% of the song is loaded. 
3. Network is disconnected.
4. After reaching 30% the music stops, but I am getting no errors, or callbacks. The song is also still considered to be "playing".  The only semi-relevant console.log I am getting from SoundManager, in debug mode, is the `stalling` event.

Here is what it looks like in the console (in debug mode):

```
soundmanager2.js:1270 soundManager.createSound(): Sound ID "2821" should be a string, starting with a non-numeric character
soundmanager2.js:1270 soundManager.createSound(): 2821 (http://myserver/happy-birthday.mp3)
soundmanager2.js:1268 2821: Merged options: Object {id: 2821, url: "http://myserver/happy-birthday.mp3", stream: false, autoLoad: false, autoPlay: false…}
soundmanager2.js:1272 2821: load (http://myserver/happy-birthday.mp3)
soundmanager2.js:1272 2821: loadstart
soundmanager2.js:1272 2821: durationchange (228391.778)
soundmanager2.js:1272 2821: loadedmetadata
soundmanager2.js:1272 2821: progress, 26% loaded
soundmanager2.js:1272 2821: loadeddata
soundmanager2.js:1272 2821: canplay
soundmanager2.js:1270 2821: onload()
soundmanager2.js:1272 2821: progress, 27% loaded
soundmanager2.js:1272 2821: progress, 28% loaded
soundmanager2.js:1272 2821: play()
soundmanager2.js:1272 2821: playing ♫
soundmanager2.js:1272 2821: progress, 28% loaded
soundmanager2.js:1272 2821: progress, 28% loaded
soundmanager2.js:1272 2821: progress, 28% loaded
soundmanager2.js:1272 2821: progress, 28% loaded
soundmanager2.js:1272 2821: stalled
```

So the question is how I can detect network disconnection?

The only way I see, right now, is to modify SoundManager2, add "stalling" callback and then when it occurs, try to reload the sound.

Is there a better way?

**Comment by scottschiller** [comment]
Hello! Apologies for the super-late follow-up, here.

In HTML5 land, "stalled" can also happen during regular playback - IIRC, this is the event that fires when the loading (buffering) has stalled. It doesn't necessarily mean network or playback trouble.

If playback stops reliably around 30% for this particular file, I'd take a look at the file itself; maybe playback is stopping due to some sort of decoding error that isn't being reported. If the file plays OK when you drag it right into a browser, that could suggest an issue with the network or the file itself (SM2 doesn't do anything to modify HTML5 playback or requests, really.)

If you get a fatal error that the browser cannot recover from when loading / buffering sound due to playback or preloading, you should get an error event on the sound along with an error code indicating what happened. Typically, I'd expect a decoding or unsupported error.

```
/**
   * HTML5 error codes, per W3C
   * Error code 1, MEDIA_ERR_ABORTED: Client aborted download at user's request.
   * Error code 2, MEDIA_ERR_NETWORK: A network error of some description caused the user agent to stop fetching the media resource, after the resource was established to be usable.
   * Error code 3, MEDIA_ERR_DECODE: An error of some description occurred while decoding the media resource, after the resource was established to be usable.
   * Error code 4, MEDIA_ERR_SRC_NOT_SUPPORTED: Media (audio file) not supported ("not usable.")
   * Reference: http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#error-codes
   */
```

**Comment by vitalybe** [comment]
Thank you for the detailed response. I'll check it and reopen the issue if needed.
