### ISSUE TITLE
soundmanager2 and iOS 10?

### ISSUE THREAD

**Issue by PaoloLeva** [scottschiller/SoundManager2#143]
My soundmanager2 implementation does not work anymore on my iPad. 
As I recently updated to iOS10, I wonder whether there is any known issue between SM2 and iOS10?

**Comment by PaoloLeva** [comment]
I found the issue, not directly related to SM2.

**Comment by trvbr** [comment]
@PaoloLeva -- Hey Paolo! Glad you figured this out. What was the exact issue? Was it server-response related? I'm dealing with this as well at a few college radio stations.

**Comment by PaoloLeva** [comment]
I'm not sure it will help, however here is what happened. We use MVC, and since iOS 10 when calling a controller function by clicking on an anchor link, as we did to play audio, the browser did no longer pass the information that the user was logged in. So Request.isAuthorised was false, which caused our controller to reject the request.
Since we noticed this issue only when clicking on audio link, I assumed this was related to SM2.
Good luck!

**Comment by scottschiller** [comment]
Sorry for late follow-up, here. There is one specific historic issue with iOS 10+ and SM2.

Beginning with iOS 10, there was a problem where versions of SM2 older than version 20140901 incorrectly detected the iOS version as being too old and therefore not supporting HTML5 audio. The problem was found years before iOS 10's release, but some sites may have never seen the reason to update their SM2 build, etc.

 http://www.schillmania.com/projects/soundmanager2/doc/download/#sm2-20140901
