### ISSUE TITLE
Is this project active and healthy?

### ISSUE THREAD

**Issue by matixmatix** [scottschiller/SoundManager2#157]
We're about to kickstart a new ambitious music-related platform and we're looking for a reliable and customizable player that supports all modern browsers, partial serving (to "seek" the audio track) and generally offers a pleasant user experience in the modern (mobile) web.

So far this is overall the best player could find and think it could be a nice fit. Since the web is constantly evolving, I have some concerns; there doesn't seem to be any activity on this project - most recent commits are several years old. Does this mean that integrating SoundManager2 could be a potential dead-end? 🤔  What are your plans for the future? Are issues and pull-requests regularly processed? Are there any viable alternatives for a modern web audio player?

And thank you for making SoundManager2 🙏.

**Comment by scottschiller** [comment]
Howdy! Thanks for the note.

The SoundManager project began as a prototype about 15 years ago, when I was trying to get sounds to be played from JavaScript. Back then, it was only available through a very particular JS -> Flash interface and limited to a few actions - but it worked!

In 2004, I published the original SoundManager project on my site after thinking others might find it useful. It was JS -> Flash only at that time of course, since HTML5 audio wasn't even on the horizon. ;) It was small and fast and worked generally well, but JSON hadn't been "invented" yet and XML was a thing, and so I went with what was popular at the time. 😆  http://schillmania.com/projects/soundmanager/

SoundManager 2 became a thing around 2006, with Flash 8 and the introduction of `ExternalInterface` which allowed proper calls to/from JS. This was the API I had been waiting for.

Through the years, I've spent time most weekends working on support, patches and the like for SM2. It's become quite reliable stable and battle-tested thanks to the feedback loop of bug reports, feature requests and the like from users. In the past, I would push updates every few months whether for feature updates, bug fixes or otherwise.

Over the last few years, updates have slowed as native HTML5 audio support has become quite stable and the Web Audio API has picked up steam. Mobile devices still place restrictions on audio playback etc., but they generally work well when the user initiates playback.

I have been busy with professional work and not on my computer nor working on side projects on weekends, so SoundManager 2 has not had regular updates for quite a while. This said, SM2 has been useful and as long as it's still relevant to developers, I am very thankful to see it implemented on a lot of large sites. Your note reminded me that I do need to push a late update, because activity (or lack thereof) on FOSS-ish projects is also seen as an indicator of health.

Within the last several years I moved to semi-annual and then annual updates , and it's now been almost two years out without a major release at this point(!) - largely, the library itself is reliable and has few bugs. Issues with HTML5 playback are often regressions or bugs in browsers, or issues with the way MP3s etc. are served over the wire as the library doesn't control HTTP requests or decoding. SM2 uses HTML5 by default with a Flash fallback, and is ~11 KB over the wire with gzip.

If I were to do a refactor at this point, I'd drop all the Flash stuff and just make it a nice wrapper around the HTML5 audio API. It is nice for folks who may need to support legacy browsers, IE 8 and the like, but those are increasingly a micro-fraction of users.

Your comment reminds me that I need to get another update in, working in the changes I've had on a development branch for some time, and reviewing open PRs etc. Thanks! 🙇

**Comment by rawzone** [comment]
Thanks for the update (And question @matixmatix). I'm currently starting quite a big project and also looking for "the best" audio player for the job - Which lead me here.

So glad to see a large comprehensive response to the concern of the state of the project - As it was my first check as well.
- [x] How active is the project.
- [x] Does bugs get reported, responded to and closed.
- [x] Does it have well written documentation.

So thanks for helping me pick the right tool for the job.

**Comment by scottschiller** [comment]
V2.97a.20170601 is now live! Two years to the day for a revision change, with a few days for last-minute tweaks. ;) This is largely a maintenance / refresh release, given the project is quite stable - everything still works. 😅 
http://www.schillmania.com/projects/soundmanager2/doc/download/#sm2-20170601

Also on npm, of course.
https://www.npmjs.com/package/soundmanager2/

**Comment by samayo** [comment]
is it still being maintained?
