### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by teslimef** [scottschiller/SoundManager2#213]
Hello Sir! I wish to make a logo for your Project that you will love, will you permit me sir?

**Comment by chrisb219** [comment]
Yes


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: teslimef <notifications@github.com> Date: 5/19/18  6:20 PM  (GMT-07:00) To: scottschiller/SoundManager2 <SoundManager2@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [scottschiller/SoundManager2] Logo (#213) 
Hello Sir! I wanna make a logo for your Project, will you permit me sir

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/scottschiller/SoundManager2/issues/213","url":"https://github.com/scottschiller/SoundManager2/issues/213","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/scottschiller/SoundManager2","title":"scottschiller/SoundManager2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/scottschiller/SoundManager2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Logo  (#213)"}],"action":{"name":"View Issue","url":"https://github.com/scottschiller/SoundManager2/issues/213"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Logo  (#213)",
"sections": [
{
"text": "",
"activityTitle": "**teslimef**",
"activityImage": "https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png",
"activitySubtitle": "@teslimef",
"facts": [
{
"name": "Repository: ",
"value": "scottschiller/SoundManager2"
},
{
"name": "Issue #: ",
"value": 213
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"scottschiller/SoundManager2\",\n\"issueId\": 213,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"scottschiller/SoundManager2\",\n\"issueId\": 213\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/scottschiller/SoundManager2/issues/213"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 337094913\n}"
}
],
"themeColor": "26292E"
}
