### ISSUE TITLE
Soundmanager2 - Bar-ui - load mp3 by url or playlist in Bar-ui.

### ISSUE THREAD

**Issue by Tranquilo1977** [scottschiller/SoundManager2#265]
Hi
first, i have really no clue what i'm doing ..but i try figure it out..
I'm working on my local host - test website

i have a Woocommerce webshop and i want to load mp3's from links into the full width - fixed - Bar-ui player)
On the single product page -> it works. 
but on the productSlist (like frontpage, or in categories with multiple products) i doesnt work.
i have broken the bar-ui in 2 (playlist and bar-ui), and i want to load the Mp3-urls INTO the full width - fixed - Bar-ui player.
I have 8 products on my frontpage and it only load the playlist correctly from the 'last' product.
every time a product load, the fixed Bar-ui set a player before each other, and i dont see that the player is working,  controlsbuttons not working.. etc.

I need to find a way to load a playlist into the player or load a mp3 separately, or the right bar-ui-view-player must be visible.
Or is their a other / better solution?

My coding: 

[Price.txt](https://github.com/scottschiller/SoundManager2/files/14323768/Price.txt)

![20240218github](https://github.com/scottschiller/SoundManager2/assets/160419842/1a516584-c9bd-44c4-b939-add0a55d55e2)

**Comment by scottschiller** [comment]
While I appreciate the detail in this report, this is not the place for it. GitHub issues are intended for bug reports e.g., with the SM2 core API, and are not a forum for support questions.

This repo has not been updated in 7 years, and I recommend a more modern API these days that uses the Web Audio API.
Notwithstanding, you can email me separately and I may be able to advise. This is older stuff, and multiple instances of the playlist UI may not work well with each other.

**Comment by Tranquilo1977** [comment]
Hi Scott..  I will go for the new modern player. I'm a bit sad to distance from SM2 after 10 years. Thnks for your effort and time.

**Comment by scottschiller** [comment]
Thanks for your understanding. SM2 has been a personal highlight for me in terms of giving back to the web, and helping make audio playback more accessible in the days before HTML5 (and the early days when support was buggy and widely varied.)

I have not ended or archived the SM2 project officially, but I feel that it delivered on its original mission - and since that time, the Web Audio spec has become standardized and very well-supported across desktop and mobile browsers alike.

I am honoured to have received many kind emails from folks over the years, who liked the SM2 API and how relatively easy it was to set up. I may write up some sort of a summary about all this, at some point. I hope that it served you well in the past as well, and I appreciate you still trying it out in 2024.
