### ISSUE TITLE
SoundManager with Flash9 won't play .aac sounds

### ISSUE THREAD

**Issue by azizantoun** [scottschiller/SoundManager2#74]
Hello,

SoundManager with Flash9 won't play my .aac files.
Demo aac files are working correctly, but my files (served from cloudfront) are not loading.
What should we do to make it work?

Thanks

**Comment by scottschiller** [comment]
Apologies for the late reply here, I was on vacation! :smile:

With AAC, I believe there are a number of sub-formats and encoding options you can go with. It's complicated because MPEG-4 is a container format, meaning you could have H.264 video + WAV audio or QuickTime and AAC audio or MP3 audio, etc., you get the idea.

Flash 9+ supports "HE-AAC (MPEG-4 Part 3)" audio, as described here.
https://helpx.adobe.com/flash/kb/supported-codecs-flash-player.html

Chances are if you're having playback issues, there is something about the encoding of your AAC that Flash doesn't like. If you get any errors from SM2 in the console etc., that may help in debugging. You _might_ get a decoding error message in the console from Flash-land, but my memory's fuzzy on this as it's been a while since I've looked at AAC and related decoding issues under Flash 9.

**Comment by scottschiller** [comment]
Closing out this ancient one, two years later. 😉 Suggest reviewing AAC encoding, and HTTP responses to be safe if issues persist; HTML5 should be able to play this on most devices, these days.
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#serving-audio
