### ISSUE TITLE
Flac support?

### ISSUE THREAD

**Issue by tchoulihan** [scottschiller/SoundManager2#76]
I'm building a music app, and flac support would be really great. Doing a search of torrents, FLAC is second in popularity behind mp3.

Edit: Not sure if this might help, a javascript library for playing flac:
https://github.com/audiocogs/aurora.js/

**Comment by scottschiller** [comment]
Hello! Pardon late reply, vacation etc. :smile:

Native FLAC support may be available to HTML5, _if_ the user has installed the FLAC plugin at a level that the OS and browser can access it. In my case, I get FLAC because I installed a plugin on my Mac at the system library level so that it works in iTunes and Safari.

I could add FLAC as a file format that SM2 checks for, but it's probably not worth doing at this point. Doing a quick test, dragging and dropping a FLAC file into Chrome results in a file download - so it appears that even Chrome doesn't have HTML5-based support for FLAC. :person_with_pouting_face: 

I don't have plans to implement a JS-based FLAC decoding library as it's highly-specialized and requires Web Audio API-level support, which is beyond the scope of SM2 at this time. The Web Audio API is also not in IE 11, so support is somewhat limited at present.
http://caniuse.com/#search=web%20audio%20api

The Aurora implementation is impressive, I should add - but it's a totally different approach from the way SM2 was originally designed and works. SM2 is OK for MP3, MP4 and AAC/WAV etc., but for FLAC you'd be better off passing those files to the aurora.js API and letting it handle playback of those.

**Comment by tchoulihan** [comment]
@scottschiller That's understandable, It does seem strange that FLAC isn't supported yet as part of html5 audio. Especially considering its the 2nd most popular song format behind mp3s. 

Using aurora as a pure js implementation of an audio player sounds like a great idea instead of waiting for more standards. Have you thought about making sm2 optionally use it for the back end? That way we could get support for a lot more audio formats.

**Comment by kazz888** [comment]
FLAC is a must! i'd love to have add it to my website

**Comment by stouch** [comment]
Hi! 🆙 
https://liliputing.com/2017/01/firefox-chrome-add-native-flac-lossless-audio-webgl-2-0.html

"Both Firefox 51 and Chrome 56 include support native support for FLAC (Free lossless audio codec) and WebGL 2.0 graphics."

Will soundManager handle soon flac support ?

**Comment by scottschiller** [comment]
@stouch: Ah, good to know Firefox will have it also! Yes, SM2 wraps HTML5 sound and existing versions should be able to play FLAC where supported, provided you give it the proper MIME type.

I can also add FLAC as one of the known sound types that SM2 checks for on start.

More here where someone asked about Chrome.
https://github.com/scottschiller/SoundManager2/issues/148#issuecomment-275932823
