### ISSUE TITLE
Issues scrubbing with position / durationEstimate

### ISSUE THREAD

**Issue by ummjackson** [scottschiller/SoundManager2#80]
So this one has been driving me crazy... Check out what I have setup at: http://dev.estate/audio

I'm rigging up SoundManager2 to work with Waveform.js and it's going well, but the second you try to scrub you'll realize that things go out of sync on Chrome + Firefox. Click somewhere before a larger peak and you'll see what I mean. 

In Safari and Opera, things work fine. Any ideas?

**Comment by tchoulihan** [comment]
If you're talking about seeking, I'm also having some problems in certain browsers. I'm finding that if you're not using apache to serve up the audio, then you have to use a lot of response headers to make it work.

**Comment by ummjackson** [comment]
Bizarre... It's even working in IE, so color me shocked. 

@tchoulihan - I've tried serving up from NGINX and local file system, but not Apache. What sort of headers should I give a shot?

Kind of crazy, I've tested a plain old HTML5 <audio> element and it works fine.

**Comment by tchoulihan** [comment]
Here are some main ones:
```java
res.header("Accept-Ranges",  "bytes");
res.header("Content-Length", String.valueOf(mp3.length())); 
res.header("Content-Range", contentRangeByteString(mp3, range));
res.header("Content-Disposition", "attachment; filename=\"" + mp3.getName() + "\"");
```
and the contentrangeBytestring:
```java
		String[] ranges = range.split("=")[1].split("-");
		log.info(range);
		log.info("ranges[] = " + Arrays.toString(ranges));

		Integer chunkSize = 1000;
		Integer from = Integer.parseInt(ranges[0]);
		Integer to = chunkSize + from;
/		if (to >= mp3.length()) {
			to = (int) (mp3.length() - 1);
			to = (int) (mp3.length());
		}
		if (ranges.length == 2) {
			to = Integer.parseInt(ranges[1]);
		}

		String responseRange = "bytes " + from + "-" + to + "/" + mp3.length();
```

**Comment by ummjackson** [comment]
@tchoulihan Where are you setting these headers? I'm already supplying everything but the accept-ranges from NGINX.

@scottschiller - any ideas?

**Comment by tchoulihan** [comment]
I don't use nginx so I couldn't tell you. I'm using an embedded jetty server for my website above.

**Comment by ummjackson** [comment]
Actually, I **am** providing accept-ranges... 

![image](https://cloud.githubusercontent.com/assets/6212609/8309729/d534e580-1980-11e5-980a-4e5df1864477.png)

I'm baffled...

**Comment by ummjackson** [comment]
+ tested with audio served directly from S3, and still seeing the issue. If you don't seek/scrub in Chrome then everything is fine, which leads me to believe it's something to do with setPosition being called that goes wacky. 

Any help appreciated.

**Comment by scottschiller** [comment]
Late to the party, apologies.

There has been a recent report of some playback issues in Chrome/Chromium when seeking, IIRC, so that may be worth considering.

In any case, I recommend reviewing the notes on Serving audio to HTML5 clients; as you have found, HTML5 clients are particular about HTTP responses. I have some general notes and findings, though I will preface all of this with the disclaimer that byte ranges / partials are a whole other can of worms whose innards I'm not experienced with. :wink: 
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#serving-audio

HTML5 clients will try to negotiate for byte serving (range/partials) with the first request, and _should_ fall back to traditional "progressive" single-request download-style if the server does not indicate support. That said, browsers default to byte serving because it's more efficient and perhaps there are some edge cases hiding in the fallback case. /shrug.

**Comment by ummjackson** [comment]
@scottschiller - thanks for the detailed response... I spent this evening trying to debug this and ended up finding the root cause: mp3 files with ID3 tags / embedded video frames / hidden album art. This screws with the way Chrome is calculating duration from what I can tell. 

To diagnose this, I actually ended up building my own janky HTML5 <audio> element player to see if I experienced the same issues - sure enough I did. A simple re-encode using `ffmpeg -i tagged.mp3 -vn -codec:a copy -map_metadata -1 out.mp3` fixes the problem. 

Thanks everyone!

**Comment by scottschiller** [comment]
Glad you sorted it; boourns on ID3 with embedded binary cruft. IIRC that is a valid use of the format, it's presumably somewhat-complex and an edge case etc. In this case, Chrome _might_ look at the bitrate and extrapolate duration based on the byte size of the total file (in this case, including the .JPEG or what have you hiding in the ID3.) Computers are hard. ;)
