### ISSUE TITLE
Semver versioning

### ISSUE THREAD

**Issue by mondalaci** [scottschiller/SoundManager2#85]
npm mandates the use of [semver](http://semver.org/) and the current version number "2.97.20150601a" hardly complies. Any plans to adopt semver?

**Comment by scottschiller** [comment]
Sorry, this was _intended_ to be semver-compliant; the original release was correct, and then I found a last-minute error and bumped the version to include "a" as I couldn't overwrite the original push.

It didn't occur to me that adding "a" would invalidate at the time, nor did I expect npm to allow me to publish a version string that was not considered valid. ;)

If it's important, I can push a "new" version which complies - otherwise, I'll wait for the next release.

**Comment by scottschiller** [comment]
Tangentially, I just found this - which while impractical, is mildly amusing. :grin: 
http://drone-ver.org/

**Comment by mondalaci** [comment]
Not a major issue, merely a good-to-have so you're welcome to wait for the new version. The Drone Ver site is hilarious. :)

Keep it up!

**Comment by scottschiller** [comment]
Side note - I've just pushed V2.97a.20170601 here to Github, the web and npm - I fixed up the `config.json` to a proper 3-clause BSD license and got a proper `README.md` among other things. Version should be properly semver-compliant, but please let me know if not. 😝
