### ISSUE TITLE
peakData different variable type than eqData

### ISSUE THREAD

**Issue by stevmark61** [scottschiller/SoundManager2#98]
This is more of a comment than an issue.

Concerns: 360player.js

// GIANT HACK: use EQ spectrum data for bass frequencies
        eqSamples = 3;
        for (i=0; i<eqSamples; i++) {
          nPeak = (nPeak||oSound.eqData[i]);
        }...

I don't know if it's me, my browser or my computer, but peakData is numeric and eqData[x] is a string so no way of combining or comparing the two.

Problem resolved by peakFloat(eqData[x]) to transform it to numeric.

**Comment by scottschiller** [comment]
Oh, interesting! You mean `parseFloat()`, I assume?

Sorry this code is a little hackish as noted, it's legacy Flash/JS stuff under the hood to make that work. 

Side thought / sausage-making note: Flash's ExternalInterface bridge does some pretty crazy stuff when passing native ActionScript arrays over to JS (serializing via XML), so instead of a huge XML structure for arrays, I pass the array as a comma-delimited string from ActionScript. Then it's one XML entry as opposed to 256 <array><item> pairs or what have you. :smile:

**Comment by scottschiller** [comment]
Sorry for super-late update - closing this out as the eqData shiz is quite old and only applies to Flash 9, which is "basically" dead these days. 😉 If this is still relevant, I can throw a `parseFloat()` in there with the next release.
